name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Container thomasweise/texlive
    container:
      image: thomasweise/texlive
      options: --user root

    steps:
    - uses: actions/checkout@v4

    # Install pyvenv
    - name: Install pyvenv
      run: apt-get update && apt-get install -y python3-venv

    # Install pip
    - name: Install pip
      run: python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip

    - name: Compile
      run: make compile
