name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Container thomasweise/texlive
    container:
      image: thomasweise/texlive
      options: --user root

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: make actions
