name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Container thomasweise/texlive
    container:
      image: texlive/texlive:latest
      options: --user root

    steps:
    - uses: actions/checkout@v4

    # Install pyvenv
    - name: Install pyvenv
      run: apt-get update && apt-get install -y python3-venv

    # Install InkScape
    - name: Install InkScape
      run: apt-get update && apt-get install -y inkscape

    - name: Compile
      run: make compile
