name: Makefile CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  actions: write
  packages: write
  deployments: write

jobs:
  build:

    runs-on: ubuntu-latest

    # Container thomasweise/texlive
    container:
      image: texlive/texlive:latest
      options: --user root

    steps:
    - uses: actions/checkout@v4

    # Install pyvenv
    - name: Install pyvenv
      run: apt-get update && apt-get install -y python3-venv

    # Install InkScape
    - name: Install InkScape
      run: apt-get update && apt-get install -y inkscape

    # Compile
    - name: Compile
      run: make compile

    # Save artifacts (PDF)
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PDFs
        path: |
          Output/English/Main.pdf
          Output/German/Main.pdf

    # Save artifacts (SVG)
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SVGs
        path: |
          Build/Images/*.svg

    # English PDF Single Artifact
    - name: English PDF Single Artifact
      uses: actions/upload-artifact@v4
      with:
        name: English PDF
        path: Output/English/Main.pdf

    # German PDF Single Artifact
    - name: German PDF Single Artifact
      uses: actions/upload-artifact@v4
      with:
        name: German PDF
        path: Output/German/Main.pdf
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Output/English/Main.pdf
        asset_name: English.pdf
        tag: ${{ github.ref }}
        overwrite: true
        body: "English PDF"

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Output/German/Main.pdf
        asset_name: German.pdf
        tag: ${{ github.ref }}
        overwrite: true
        body: "German PDF"